name: Check Precipitation Change

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour

jobs:
  check-precipitation-change:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requirements.txt

      - name: Run check precipitation change script
        run: python your_script.py
        env:
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          MY_PHONE_NO: ${{ secrets.MY_PHONE_NO }}

